import localFont from "next/font/local";
import "../style/globals.css";
import Footer from "../components/includes/page";
import Navbar from "../components/includes/navbar/page";
import { footerItems } from "../utilities/StaticString";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "NVIDIA NIM:Apis To Deploy Generative Ai Models Anywhere",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/images/favicon.png" />
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Navbar />
                {children}
                <Footer data={footerItems} />
            </body>
        </html>
    );
}
